[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-worker]
command=php /var/www/artisan queue:work redis --queue=job,app,listeners,mail,cache --sleep=3 --tries=3
process_name=%(program_name)s_%(process_num)02d
numprocs=5
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker.log

[program:laravel-rabbitmq-worker]
command=php /var/www/artisan queue:work rabbitmq --queue=default --sleep=3 --tries=3
process_name=%(program_name)s_%(process_num)02d
numprocs=3
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/rabbitmq-worker.log

[program:laravel-reverb]
command=php /var/www/artisan reverb:start
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/reverb.log
