services:
    nginx:
        image: nginx:alpine
        container_name: app-nginx
        restart: unless-stopped
        ports:
            - "3000:80"
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/
        depends_on:
            -   app
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: app
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www/
        depends_on:
            -   postgres
        networks:
            - app-network

    postgres:
        image: postgres:latest
        container_name: app-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5433:${DB_PORT}"
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: app-redis
        restart: always
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        volumes:
            - ./redis:/data
        ports:
            - "6379:6379"
        networks:
            - app-network

    adminer:
        image: adminer:latest
        container_name: app-adminer
        restart: always
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_DB_DRIVER: ${DB_CONNECTION}
            ADMINER_DEFAULT_DB_HOST: ${DB_HOST}:${DB_PORT}
            ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
            ADMINER_DESIGN: nette
            ADMINER_DEFAULT_SERVER: ${DB_HOST}:${DB_PORT}
        depends_on:
            -   postgres
        networks:
            - app-network


    es01:
        image: elasticsearch:8.18.0
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data01:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        networks:
            - elastic
            - app-network

    kib01:
        image: kibana:8.18.0
        container_name: kib01
        ports:
            - "5601:5601"
        environment:
#            ELASTICSEARCH_URL: http://localhost:9200
            ELASTICSEARCH_HOSTS: http://es01:9200
        depends_on:
            - es01
        networks:
            - elastic
            - app-network

networks:
    app-network:
        driver: bridge
    elastic:
        driver: bridge

volumes:
    pgdata:
        driver: local
    data01:
        driver: local
