services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: app-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "9000:9000"
            - "9001:9001"
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/certs:/etc/nginx/certs
            - ./:/var/www/
        depends_on:
            - app
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: app
        restart: unless-stopped
        ports:
            - "3030:3030"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www/
        depends_on:
            - postgres
            - redis
            - minio
        networks:
            - app-network

    postgres:
        image: postgres:latest
        container_name: app-postgres
        restart: unless-stopped
        user: "postgres"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5433:${DB_PORT}"
        healthcheck:
            test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'" ]
            interval: 10s
            timeout: 3s
            retries: 3
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    adminer:
        image: adminer:latest
        container_name: app-adminer
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_DB_DRIVER: ${DB_CONNECTION}
            ADMINER_DEFAULT_DB_HOST: ${DB_HOST}:${DB_PORT}
            ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
            ADMINER_DESIGN: nette
            ADMINER_DEFAULT_SERVER: ${DB_HOST}:${DB_PORT}
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - app-network

    mailhog:
        image: mailhog/mailhog
        container_name: app-mailhog
        restart: unless-stopped
        ports:
            - "1025"
            - "8025:8025"
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: app-redis
        restart: unless-stopped
        user: "redis"
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            - "6379:${REDIS_PORT}"
        volumes:
            - redis_data:/data
        networks:
            - app-network

    redisinsight:
        image: redislabs/redisinsight:latest
        container_name: app-redisinsight
        restart: unless-stopped
        ports:
            - "5540:${REDISINSIGHT_PORT}"
        volumes:
            - redisinsight:/db
        networks:
            - app-network

    typesense:
        image: typesense/typesense:29.0
        container_name: app-typesense
        restart: unless-stopped
        command: '--data-dir /data --api-key=xyz --enable-cors'
        ports:
            - "8108:${TYPESENSE_PORT}"
        volumes:
            - typesense_data:/data
        networks:
            - app-network

    dashboard:
        image: ghcr.io/lewynation/typesense-admin-dashboard:latest
        container_name: app-dashboard
        restart: unless-stopped
        ports:
            - "3005:3000"
        networks:
            - app-network

    minio:
        image: minio/minio:RELEASE.2025-04-22T22-12-26Z
        container_name: app-minio
        restart: unless-stopped
        volumes:
            - minio_data:/data
            - minio_config:/root/.minio
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
            MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
            MINIO_DOMAIN: ${MINIO_DOMAIN}
        command: server /data --console-address ":9001"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local
    redisinsight:
        driver: local
    typesense_data:
        driver: local
    minio_data:
        driver: local
    minio_config:
        driver: local
