services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: app-nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/certs:/etc/nginx/certs
            - ./:/var/www/
        depends_on:
            - app
        networks:
            - app-network
    #            - microlib_proxy

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: app
        restart: always
        #        user: 33:33
        ports:
            - "5173:5173"
            - "3030:3030"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www/
        depends_on:
            - postgres
        networks:
            - app-network

    #    mailhog:
    #        image: mailhog/mailhog
    #        container_name: app-mailhog
    #        ports:
    #            - "1025"
    #            - "8025:8025"
    #        networks:
    #            - app-network

    psalm:
        image: ghcr.io/danog/psalm:latest
        container_name: app-psalm
        volumes:
            - .:/app
        working_dir: /app
        #        command: /composer/vendor/bin/psalm --no-cache
        networks:
            - app-network

    postgres:
        image: postgres:latest
        container_name: app-postgres
        restart: always
        user: "postgres"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5433:${DB_PORT}"
        healthcheck:
            test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'" ]
            interval: 10s
            timeout: 3s
            retries: 3
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: app-redis
        restart: always
        user: "redis"
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            - "6379:${REDIS_PORT}"
        volumes:
            - redis_data:/data
        networks:
            - app-network
    #            - cache_proxy

    redisinsight:
        image: redislabs/redisinsight:latest
        container_name: app-redisinsight
        ports:
            - "5540:${REDISINSIGHT_PORT}"
        volumes:
            - redisinsight:/db
        restart: always
        networks:
            - app-network

    adminer:
        image: adminer:latest
        container_name: app-adminer
        restart: always
        environment:
            ADMINER_DEFAULT_DB_DRIVER: ${DB_CONNECTION}
            ADMINER_DEFAULT_DB_HOST: ${DB_HOST}:${DB_PORT}
            ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
            ADMINER_DESIGN: nette
            ADMINER_DEFAULT_SERVER: ${DB_HOST}:${DB_PORT}
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - app-network

    typesense:
        image: typesense/typesense:29.0
        container_name: app-typesense
        restart: always
        #        user: 33:33
        command: '--data-dir /data --api-key=xyz --enable-cors'
        ports:
            - "8108:${TYPESENSE_PORT}"
        volumes:
            - typesense_data:/data
        networks:
            - app-network

    dashboard:
        image: ghcr.io/lewynation/typesense-admin-dashboard:latest
        container_name: app-dashboard
        restart: always
        ports:
            - "3005:3000"
        networks:
            - app-network

#    sequin:
#        image: sequin/sequin:latest
#        container_name: app-sequin
#        restart: always
#        ports:
#            - "7376:7376"
#        environment:
#            PG_HOSTNAME: ${DB_HOST}
#            PG_DATABASE: ${DB_DATABASE}
#            PG_PORT: ${DB_PORT}
#            PG_USERNAME: ${DB_USERNAME}
#            PG_PASSWORD: ${DB_PASSWORD}
#            PG_POOL_SIZE: 20
#            SECRET_KEY_BASE: wDPLYus0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If
#            VAULT_KEY: 2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY=
#            REDIS_URL: http://app-redis:6379
#            CONFIG_FILE_PATH: /config/playground.yml
#        volumes:
#            - ./playground.yml:/config/playground.yml
#        depends_on:
#            redis:
#                condition: service_started
#            postgres:
#                condition: service_healthy
#        networks:
#            - app-network

networks:
    app-network:
        driver: bridge
#    cache_proxy:
#        external: true
#    microlib_proxy:
#        external: true

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local
    redisinsight:
        driver: local
    typesense_data:
        driver: local
